project:
  type: book

book:
  title: "PSCI 2075 Recitation Handout"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - docs/handout.qmd
    - docs/outline.qmd
    - docs/01_setup.qmd
    - docs/02_anatomy.qmd
    - docs/03_file_structure.qmd
    - docs/04_run_code.qmd
    - docs/05_quarto.qmd
    - docs/06_r_syntax_basics.qmd
    - docs/07_loading_data.qmd
    - docs/08_summarizing_data.qmd
    - docs/references.qmd
    page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2021-2023 Damon Charles Roberts</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span> 
  google-analytics: "G-8Z2BLG3VEE"
toc-depth: 2
bibliography: references.bib

format:
  html:
    theme:
      - journal
      - assets/custom.scss
    css: styles.css
    code-copy: true

execute:
  freeze: auto