project:
  type: book

book:
  title: "PSCI 2075 Recitation Handout"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - docs/handout.qmd
    - docs/outline.qmd
    - docs/01_setup.qmd
    - docs/02_anatomy.qmd
    - docs/03_file_structure.qmd
    - docs/04_run_code.qmd
    - docs/05_quarto.qmd
    - docs/06_r_syntax_basics.qmd
    - docs/07_loading_data.qmd
    - docs/references.qmd
  google-analytics: "G-8Z2BLG3VEE"
toc-depth: 2
bibliography: references.bib

format:
  html:
    theme:
      - journal
      - assets/custom.scss
    css: styles.css
    code-copy: true

execute:
  freeze: auto