project:
  type: book

book:
  title: "PSCI 2075 Recitation Handout"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - references.qmd
toc-depth: 2
bibliography: references.bib

format:
  html:
    theme:
      - journal
      - assets/custom.scss
execute:
  freeze: auto