project:
  type: book

book:
  title: "PSCI 2075 Recitation Handout"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - docs/handout.qmd
    - docs/01_setup.qmd
    - docs/02_anatomy.qmd
    - docs/03_run_code.qmd
    - docs/04_quarto.qmd
    - docs/05_r_syntax_basics.qmd
    #- 06_loading_data.qmd
    - docs/references.qmd
toc-depth: 2
bibliography: assets/references.bib

format:
  html:
    theme:
      - journal
      - assets/custom.scss
    css: styles.css
    code-copy: true

execute:
  freeze: auto