# {{< fa timeline >}} Outline: What we've done in recitation

<div class="tenor-gif-embed" data-postid="18564553" data-share-method="host" data-aspect-ratio="1.57635" data-width="100%"><a href="https://tenor.com/view/charlie-day-gif-18564553">Charlie Day GIF</a>from <a href="https://tenor.com/search/charlie-gifs">Charlie GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>


## Week 1

- Slides: [Week 1 Slides](../slides/week_1.html)
- Recitation Policies: [Recitation Policies](handout.qmd)
    - Sign up term paper group: [Recitation Policies](handout.qmd#recitation-information) (under recitation information, click on {{< fa file-csv >}} icon to fill out google sheet)
- Setting up R and RStudio: [R Setup](01_setup.qmd)

## Week 2

- Slides: [Week 2 Slides](../slides/week_2.html)
- Finalizing groups: [Recitation Policies](handout.qmd#recitation-information) (under recitation information, click on the {{< fa file-csv >}} icon to fill out google sheet)
- Make sure everyone has R and RStudio set up. [R Setup](01_setup.qmd)
- Go over the anatomy of RStudio. [RStudio Anatomy](02_anatomy.qmd)
- Go over file structure on computers. [Computer file structure](03_file_structure.qmd)
- Go over ways to run R code. [Writing R code](04_run_code.qmd)
- Go over basic R syntax. [Basic R syntax](06_r_syntax_basics.qmd)

## Week 3

- Attendance
- Go over how to load the datasets for the class. [Load data](07_loading_data.qmd)
- Go over describing variables in your data. [Descriptive statistics](08_summarizing_data.qmd)
- (If time) get groups together to work on Group Assignment 1.

## Week 4

- Attendance
- Introduction to [cleaning variables](09_simple_data_cleaning.qmd)
- [Bivariate (two variables) descriptive statistics](10_simple_bivariate_analyses.qmd)
- Group work

## Week 5

- Attendance
- Review
- [Group assignment 1 debrief](11_group_assignment_one.qmd)
- Group work

## Week 6

- Attendance
- Review
- [Conditional analyses](12_bivariate_expectations.qmd)
- Group work

## Week 7

- Attendance
- Review
- [Bivariate regression](13_bivariate_regression.qmd)
- Group work

## Week 8

- Attendance
- Review
- [Multivariate regression](14_multivariate_regression.qmd)
- Group work

## Week 9

- Attendance
- Point out [dichotomous independent variable interpretation](15_dichotomous_iv.qmd) and [interaction models](16_interactions.qmd)
- [Midterm review](17_midterm_review.qmd)
- Group work

## Week 10

- Midterm

## Week 11

- Attendance
- [Population Distributions](18_population_distribution.qmd)
- [Sample Distributions](19_sample_distribution.qmd)
- [Sampling Distributions](20_sampling_distributions.qmd)
- [Inference and Confidence Intervals](21_inference_and_confidence_intervals.qmd)
- Group work

## Week 12

- Damon out of town for conference

## Week 13

- Attendance
- Some comments on common areas for improvements
- [Post-estimation diagnostics](22_post-estimation_diagnostics.qmd)

## Week 14

- Attendance
- Highlighting a real world example of all of this stuff.
- [Logistic regression](23_logits.qmd)
- Group work

## Week 15

- [Final exercise](24_closing_exercise.qmd)
- Answering questions and big study sesh!